name: Rust

on:
  workflow_dispatch:
  pull_request:
  push:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  tests:
    name: Tests on ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v1.3.0
    - name: Run cargo check without any default features
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --locked --release --no-default-features
    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --locked --release

  clippy:
    name: Run Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1.3.0
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets -- --deny warnings

  fmt:
    name: Run Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1.3.0
      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  demo:
    name: Deploy demo on netlify
    needs: [clippy, fmt, tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build wasm
        run: wasm-pack build --release --target web
      - name: Build demo
        run: (cd demo && npm install && npm run build)
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=demo/dist
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1.3.0
